### ISSUE TITLE
container-engine-for-cc-deploy observations

### ISSUE THREAD

**Issue by mythi** [confidential-containers/operator#104]
**Describe the bug**
Writing my container-engine-for-cc-deploy  observations here so that they are not forgotten:

- [x] `install_artifacts` is not idempotent. I had the install-daemon pod failing, kubernetes tried to restart the pod and `install_artifacts` tried to copy containerd over the existing binary that was already running. in the logs I could only see this copy error and not the error that originally caused the pod to fail
- [x] `label_node uninstall`. the label creation/deletion logic looks ok. who deletes `cc-preinstall/done=true` when uninstall is done?

**Comment by fidencio** [comment]
@mythi, thanks for bringing those two observations up.

The first one has been addressed by https://github.com/fidencio/container-engine-for-cc-payload/pull/3

About the second one, I do believe that as setting the label is something required by the operator, the operator should be the one removing it when the install is done. @bpradipt, do you agree with the statement?

**Comment by fidencio** [comment]
> About the second one, I do believe that as setting the label is something required by the operator, the operator should be the one removing it when the install is done. @bpradipt, do you agree with the statement?

@mythi, this is done by: https://github.com/confidential-containers/operator/blob/ccb1b7f61ab9312cde0dd53bd58a8fcb4c1f01e4/controllers/ccruntime_controller.go#L892-L924

Does the issue happen to you also when performing a successful (as in, without errors) installation / uninstallation?

**Comment by mythi** [comment]
> Does the issue happen to you also when performing a successful (as in, without errors) installation / uninstallation?

I can see they disappear so the code you pointed me to works. Thanks! I guess the follow-up question would be does the workload itself need to do the labeling (and have the service account for it) or should the operator take are of this labeling completely.

**Comment by bpradipt** [comment]
> @mythi, thanks for bringing those two observations up.
> 
> The first one has been addressed by [fidencio/container-engine-for-cc-payload#3](https://github.com/fidencio/container-engine-for-cc-payload/pull/3)
> 
> About the second one, I do believe that as setting the label is something required by the operator, the operator should be the one removing it when the install is done. @bpradipt, do you agree with the statement?

@fidencio I see that you have already shared the details. Thanks. I was out on vacation for few days :-)

**Comment by bpradipt** [comment]
> > Does the issue happen to you also when performing a successful (as in, without errors) installation / uninstallation?
> 
> I can see they disappear so the code you pointed me to works. Thanks! I guess the follow-up question would be does the workload itself need to do the labeling (and have the service account for it) or should the operator take are of this labeling completely.

Yeah. Please check this - https://github.com/fidencio/container-engine-for-cc-payload/blob/main/scripts/container-engine-for-cc-deploy.sh#L60

It took me some time to figure out how the different pieces are working together :-(. 

In the short term, we really need to document the install/un-install state management and update the payload image [doc](https://github.com/confidential-containers/operator/blob/main/docs/PAYLOAD_IMAGE.md) with labelling requirements.

In the long term, I do think the (un)install state management using labels should be improved. 
Looking forward to suggestions.

**Comment by fidencio** [comment]
@mythi, I'm closing this one but feel free to re-open it in case something is still missing.

**Comment by mythi** [comment]
@fidencio all good, thanks!
