### ISSUE TITLE
Using v0.1.0 results in using the operator image with the `latest` tag

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/operator#118]
**Describe the bug**
Using v0.1.0 results in using the operator image with `latest` tag

**To Reproduce**
Following the instructions in the README

**Describe the results you expected**
Instead of `latest` tag, `v0.1.0` should have been used.

**Describe the results you received:**
Operator deployed using image: quay.io/confidential-containers/operator:latest instead of image: quay.io/confidential-containers/operator:v0.1.0
 
**Additional context**
The offending line: https://github.com/confidential-containers/operator/blob/v0.1.0/deploy/deploy.yaml#L3692

**Comment by mythi** [comment]
Same as #103

**Comment by bpradipt** [comment]
Thanks @mythi . Closing this as duplicate of #103
