### ISSUE TITLE
Enable to publish multi-arch operator image

### ISSUE THREAD

**Issue by BbolroC** [confidential-containers/operator#131]
**Is your feature request related to a problem? Please describe.**
Currently, an operator image is available only for `x86_64` at https://quay.io/repository/confidential-containers/operator.
I would be good to have it available for other architectures (`aarch64`, `ppc64le` and `s390x`) with the same tag.

**Describe the solution you'd like**
1. Turn on a `docker buildx` functionality on the GHA [workflow](https://github.com/confidential-containers/operator/blob/main/.github/workflows/docker-publish.yml#L52).

```
$ # install qemu-user-static
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
$ # create/use a new builder for multi-arch support
$ docker buildx create --driver-opt network=host --use --name container-builder
$ docker buildx inspect --bootstrap
$ docker buildx use container-builder
$ # enable buildx
$ export DOCKER_BUILDKIT=1
```
3. Change a base image from `bitnami/golang` to `golang:1.18` (one compatible with all architectures)
4. Make a dedicated script for multi-arch image build (or within the GHA workflow) with a tag ending with a architecture name
5. Make `Dockerfile` configurable with an argument named `DOCKER_ARCHES` which is used for `GOARCH` in `go build`.
6. Consolidate all architecture specific docker images into one tag (via `docker manifest`)

**Additional context**
Multi-arch support for `payload image` (e.g. `quay.io/confidential-containers/runtime-payload`) will be handled in the `CCv0` branch of the `kata-containers` project (https://github.com/kata-containers/kata-containers/issues/5660). The Ansible test will be followed after this issue. 

I look forward to feedback from you.

cc: @fidencio @stevenhorsman @hbrueckner

**Comment by fidencio** [comment]
I'd be happy to see this happening!
