### ISSUE TITLE
Add support to provision SNP components

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/operator#146]
**Is your feature request related to a problem? Please describe.**

Add support to the operator so that it can provision a node with SNP support and create a SNP runtimeclass.

**Describe the solution you'd like**

Package components needed like other runtimeclasses. The work will mostly be based off of https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md guide.

---

- Operator tests is a good start instead of the kata-cc because there is no k8s.
- Bundle:
    - A Containerd config file
        - QEMU Path, Kernel Path
        - SNP Guest flags
        - ...
    - Kata PR https://github.com/kata-containers/kata-containers/pull/5796
    - Config SEV SNP: https://github.com/kata-containers/kata-containers/pull/6135
    - https://github.com/kata-containers/kata-containers/pull/6124
    - https://github.com/kata-containers/kata-containers/pull/6062
    - https://github.com/kata-containers/kata-containers/pull/5850
    - OVMF https://github.com/kata-containers/kata-containers/pull/5850. We will need an upstream OVMF.
    - QEMU: Built with the AMD branch: https://github.com/kata-containers/kata-containers/issues/6061

**Comment by surajssd** [comment]
cc: @fitzthum for more context

**Comment by jepio** [comment]
Operator PR:
- #187

**Comment by wainersm** [comment]
How do you plan to change CI to cover SNP as well?

**Comment by jepio** [comment]
A new jenkins job, and we'll convert one of the AMD nodes to be SNP capable. But I don't think we'll get that done for v0.5.0.

**Comment by ryansavino** [comment]
PRs for SNP testing:
https://github.com/kata-containers/tests/pull/5594
https://github.com/confidential-containers/operator/pull/197

**Comment by fidencio** [comment]
We can close this one, as it's already in.
