### ISSUE TITLE
Trying to use the operator on azure AKS without success....

### ISSUE THREAD

**Issue by quertenmont** [confidential-containers/operator#148]
Hello,

I am trying to make use of the operator on azure AKS cluster (v1.24.6),  but my pod with runtime annotation failed to start

I followed the intall instructions and installed V0.2.0 release of the operator.
I used the following image for the cc-operator-daemon-install: quay.io/confidential-containers/runtime-payload:kata-containers-5b7009f2f9cdb39099b97a4f868b53ec9f3c383f

Some checks, that everything is properly installed:

1) my nodes have the worker role
```
kubectl get node -A
NAME                                   STATUS   ROLES          AGE     VERSION
aks-agentpool2-14953537-vmss000000     Ready    agent,worker   3h43m   v1.24.6
aks-cvmnodepool-20314985-vmss000000    Ready    agent,worker   3h44m   v1.24.6
```

2) the operator is properly running
```
kubectl get pods -n confidential-containers-system
NAME                                              READY   STATUS    RESTARTS   AGE
cc-operator-controller-manager-79797456f6-7j854   2/2     Running   0          168m
cc-operator-daemon-install-4wpb7                  1/1     Running   0          103m
cc-operator-daemon-install-bp8nz                  1/1     Running   0          6m17s
cc-operator-pre-install-daemon-9lphw              1/1     Running   0          6m17s
cc-operator-pre-install-daemon-dkpx4              1/1     Running   0          119m
```

3) runtime classes are available:
```
kubectl get runtimeclass
NAME                    HANDLER                 AGE
kata                    kata                    105m
kata-clh                kata-clh                105m
kata-clh-tdx            kata-clh-tdx            105m
kata-clh-tdx-eaa-kbc    kata-clh-tdx-eaa-kbc    105m
kata-qemu               kata-qemu               105m
kata-qemu-sev           kata-qemu-sev           105m
kata-qemu-tdx           kata-qemu-tdx           105m
kata-qemu-tdx-eaa-kbc   kata-qemu-tdx-eaa-kbc   105m
```

I then tried to add the "runtimeClassName: kata-qemu" to the spec of some deployment, but the deployment pods do not start anymore.
kubectl describe on the affected pods lead to the following explanation:
```
  Warning  FailedCreatePodSandBox  3m19s (x298 over 8m23s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: failed to launch qemu: exit status 1, error messages from qemu log: Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: failed to initialize kvm: No such file or directory
: unknown
```
Any idea how I can resolve this on an AKS managed cluster ?

Thanks in advance for helping,
Loic

**Comment by fidencio** [comment]
@quertenmont, from this log, which is quite short, it makes me think that nested virtualiation is not enabled on your Azure instance.  Would you be able to confirm that?

**Comment by quertenmont** [comment]
Yes, indeed.  Unfortunately there is no VM available on Azure supporting
simultaneously AMD SEV and nested serialization.  So this is a dead end for
me (for now at least)

Thanks for helping
Loic

Le lun. 16 janv. 2023, 22:15, Fabiano Fidêncio ***@***.***> a
écrit :

**Comment by fidencio** [comment]
Theoretically no TEE VM supports nested, and you should give it a try on baremetal.

I'm closing the issue for now, but please, feel free to re-open it if needed.
