### ISSUE TITLE
cc-operator-daemon-install fails with upstream bundle

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/operator#183]
I have been doing some local testing with the operator. When I use the 0.4.0 bundle everything works fine, but when I switch to the upstream bundle, `cc-operator-daemon-install` fails with

    $ kubectl logs cc-operator-daemon-install-7k75x -n confidential-containers-system
    copying kata artifacts onto host
    warning: /usr/local/bin/containerd-shim-kata-qemu-v2 already exists
    warning: /usr/local/bin/containerd-shim-kata-v2 already exists
    Creating the default shim-v2 binary
    warning: /usr/local/bin/containerd-shim-kata-qemu-tdx-v2 already exists
    warning: /usr/local/bin/containerd-shim-kata-qemu-sev-v2 already exists
    warning: /usr/local/bin/containerd-shim-kata-clh-v2 already exists
    warning: /usr/local/bin/containerd-shim-kata-clh-tdx-v2 already exists
    Add Kata Containers as a supported runtime for containerd
    Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata, overwriting
    Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata.options, overwriting
    Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu, overwriting
    Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu.options, overwriting
    Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu-tdx, overwriting
    Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu-tdx.options, overwriting
    Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu-sev, overwriting
    Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu-sev.options, overwriting
    Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh, overwriting
    Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh.options, overwriting
    Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh-tdx, overwriting
    Configuration exists for plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh-tdx.options, overwriting
    Failed to connect to bus: No data available

Note final line. Could it be related to some recent dbus changes? I haven't had time to isolate yet, but dropping this issue in case someone else has run into the problem. It seems like it might also be showing up on some of the Jenkins jobs. See http://jenkins.katacontainers.io/blue/organizations/jenkins/confidential-containers-ci/detail/confidential-containers-ci/25/pipeline

@stevenhorsman @fidencio @Alex-Carter01

**Comment by mythi** [comment]
@fitzthum See #180 for a possible reason

**Comment by fitzthum** [comment]
If anyone else bumps into this problem, you can work around it in the short term by building the operator with the PR that is linked above.
