### ISSUE TITLE
Document requirements for adding new CC runtimes to the operator

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/operator#19]
Currently the operator supports Kata runtime and going forward more runtimes will get added.
It'll be useful to have some guidelines on what's required to add a new runtime.

**Comment by fidencio** [comment]
@bpradipt, @jensfr, can we close this one?

**Comment by ariel-adam** [comment]
@bpradipt can you close this issue?

**Comment by fidencio** [comment]
Closing this one, @bpradipt, feel free to re-open it if needed.
