### ISSUE TITLE
Update node label prefix

### ISSUE THREAD

**Issue by kartikjoshi21** [confidential-containers/operator#194]
For Kubernetes version greater than or equal to 1.16, node label keys in the 'kubernetes.io' or 'k8s.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io).

Update labels to be inline with latest version.

**Comment by genjuro214** [comment]
@kartikjoshi21 Do we have an issue or plan to update the label in `cloud-api-adaptor`? Daily e2e tests jobs have failed due to this change: https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/5515993957

**Comment by bpradipt** [comment]
@genjuro214 this is the equivalent on cloud-api-adaptor - https://github.com/confidential-containers/cloud-api-adaptor/pull/784
