### ISSUE TITLE
CRD for building confidential container images

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/operator#20]
Opening this issue to discuss if we need a CRD for confidential container image builds encapsulating the different CC technologies and related attestation requirements. And how do we go about it.
This is a placeholder issue to get ideas and kickstart the discussion

**Comment by bpradipt** [comment]
cc @sameo @jensfr

**Comment by Jakob-Naucke** [comment]
@bpradipt wait, are we talking _container_ images or VM images that can _host_ confidential containers?
If the former, is there really a need for
> encapsulating the dfferent CC technologies and related attestation requirements

? Wouldn't they always just be encrypted images (although I have not yet managed to push a multiarch encrypted image)?
If the latter (Kata-specific I guess), https://github.com/kata-containers/kata-containers/pull/3127 and https://github.com/kata-containers/kata-containers/pull/3199 start some things in that direction.

**Comment by bpradipt** [comment]
@Jakob-Naucke talking about container images here.  The PRs you referred is a good start from Kata runtime standpoint.

**Comment by bpradipt** [comment]
@Jakob-Naucke regarding multi-arch encrypted image support in hosted registries, as we already know there are some limitations. For example, it's possible in docker.io but not possible in hosted quay.io. Not sure about gcr.io and others. Private registries should work.  
Also, I don't think the container images will be always encrypted. Having said that I feel it's better to list down the starting assumptions and figure out if need a CRD to handle container image, potential integration into existing build (eg. tekton) pipelines. 

In the end, whatever we can do to make it easier for users to generate confidential container images without too many changes in their existing workflows.

**Comment by Jakob-Naucke** [comment]
@bpradipt I take it the primary purpose is avoiding a user having to run (somewhat delicate) `skopeo` commands to encrypt images?

**Comment by bpradipt** [comment]
The following picture gives a high-level overview of the steps involved in a typical DevOps pipeline.
![cc-image-build](https://user-images.githubusercontent.com/9287071/151530008-abb1c39a-29b3-4ccd-bac9-6a02fb087122.png)

The question is should we create a CRD to help with confidential container image build or create [reusable tekton tasks](https://github.com/tektoncd/catalog) or something else?

**Comment by fidencio** [comment]
@bpradipt, @jensfr, can we close this one?

**Comment by ariel-adam** [comment]
@bpradipt is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by fidencio** [comment]
Closing this one, @bpradipt, feel free to re-open it if needed.
