### ISSUE TITLE
Migration support with the CC operator

### ISSUE THREAD

**Issue by optimistyzy** [confidential-containers/operator#27]
Some hardware based TEE solutions may break the migration features (e.g., VM migration features). So will CC operator be aware of this which can be reported by the low level? Then users who deploy the confidential containers can know this. If the users need a flexible and scalable deployment,  they can choose the node with the TEE solution which can support the migration.

**Comment by fidencio** [comment]
I don't think we should worry much about this as, AFAIU, kata-containers has never ever supported live migration.

We can be overly cautious and plan ahead, but I don't think we need to do that right now. :-)

**Comment by optimistyzy** [comment]
@fidencio Sure. So should we close this ?

**Comment by fidencio** [comment]
Yep, I think we can.
If you want, really really want, to have migration supported we can start a thread on the kata-containers side, but for now we can close this one.

**Comment by optimistyzy** [comment]
> Yep, I think we can. If you want, really really want, to have migration supported we can start a thread on the kata-containers side, but for now we can close this one.

Got it.
