### ISSUE TITLE
Add ldoktor as part of the maintainers

### ISSUE THREAD

**Issue by fidencio** [confidential-containers/operator#312]
Lukáš has been working on improving the operator tests, and it's more than fair to have him being able to also review code that will be submitted on this front.

With this in mind, I'd like to request adding @ldoktor as part of the maintainers here.

**Comment by stevenhorsman** [comment]
+1 from me

**Comment by bpradipt** [comment]
+1

**Comment by fitzthum** [comment]
Added @ldoktor to @confidential-containers/operator-maintainers

**Comment by ldoktor** [comment]
Thank you, I'll do my best to help with the reviews (starting next week)
