### ISSUE TITLE
Add support for setting allowed_hypervisor_annotations

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/operator#335]
Recently Kata Container's kata-deploy added support for users set the allowed_hypervisor_annotations properties from configuration.toml at the installation time (see  [kata-deploy: Allow users to set hypervisor annotations](https://github.com/kata-containers/kata-containers/pull/8404)). This option is enabled if the user exports the `ALLOWED_HYPERVISOR_ANNOTATIONS` environment variable when installing kata with kata-deploy.

Not clear if we will be using that feature on CoCo, if not then this issue can be simply closed.

Cc @fidencio @BbolroC @stevenhorsman

**Comment by fidencio** [comment]
This can already be done via env vars, by setting `ALLOWED_HYPERVISOR_ANNOTATIONS` in a similar way of what's already done with AGENT_HTTPS_PROXY / AGENT_NO_PROXY and described here: https://github.com/confidential-containers/operator/blob/5e4df705a21e00d66b08256fccc2498f59296358/config/samples/ccruntime/default/kustomization.yaml#L50-L59

I do believe it will be used in CoCo, but as there's nothing for us to do, I'm closing the issue.
Feel free to re-open it if needed.

**Comment by ldoktor** [comment]
@fidencio you mentioned you expect people to be setting it, would it make sense to add it (and/or perhaps other useful vars) to the sample overlay to better emphasize what could be there? Or maybe just adding the `kata-containers/tools/packaging/kata-deploy/scripts/kata-deploy.sh` link there to mention once might be interested in tweaking those from here?
