### ISSUE TITLE
New operator-committers team

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/operator#337]
We should have a operator-committers Github team with less privileges then the current [operator-maintainers](
https://github.com/orgs/confidential-containers/teams/operator-maintainers) but with enough privileges to allow people working on CI as well as trusted devs to run CI workflows, add PR labels, assign issues to themselves.

This was originally suggested by @stevenhorsman . I hope I captured his idea well; idea that I second BTW.

Cc @BbolroC @fitzthum

**Comment by fitzthum** [comment]
This sounds like a good idea. Can we get a few more acks?

**Comment by bpradipt** [comment]
This definitely makes sense.

**Comment by stevenhorsman** [comment]
The new group has been set-up and given write access to the operator repo, so this is completed.
