### ISSUE TITLE
Operator does not run

### ISSUE THREAD

**Issue by pegahnikbakht** [confidential-containers/operator#360]
I tried to install the operator using the instructions [https://github.com/confidential-containers/operator/blob/main/docs/INSTALL.md] but it get stuck in pending phase, I tried to get the logs this is the only thing I can see in the logs: 

`Defaulted container "kube-rbac-proxy" out of: kube-rbac-proxy, manager`

How I can solve this?

**Comment by ldoktor** [comment]
Looks like double-post of https://github.com/confidential-containers/operator/issues/361 let's keep discussing it there.
