### ISSUE TITLE
remove ssh-demo

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/operator#370]
We haven't used or updated the ssh-demo CRD in a while. We don't really need it anymore with the sample-attester. Can we remove it entirely?

cc @stevenhorsman

**Comment by stevenhorsman** [comment]
I agree - it's not been maintained, so should be removed. I think we discussed it before, but that @wainersm included it a blog post, so we backed away from deleting it straight after, but that post will be fairly outdated anyway now, so I think it's safe to go ahead

**Comment by wainersm** [comment]
Hi @fitzthum @stevenhorsman !

> I agree - it's not been maintained, so should be removed. I think we discussed it before, but that @wainersm included it a blog post, so we backed away from deleting it straight after, but that post will be fairly outdated anyway now, so I think it's safe to go ahead

Correct. I plan to write a v2 of the blog post with the new non-tee runtimeclass (perhaps after 0.9.0-alpha1, or even the 0.9 GA \o/).
