### ISSUE TITLE
Add documentation on how to override the payloadImage

### ISSUE THREAD

**Issue by fidencio** [confidential-containers/operator#4]
https://github.com/confidential-containers/confidential-containers-operator/blob/main/README.md doesn't provide any instruction on how to override the payloadImage, which is currently using the released kata-deploy image (an image that doesn't have the confidential-containers bits in).

**Comment by bpradipt** [comment]
To start with, how about adding a mention of changing the payload image when creating the CR ? - https://github.com/confidential-containers/operator/blob/main/config/samples/_v1beta1_confidentialcontainersruntime.yaml#L11
