### ISSUE TITLE
CI: migrate non-TEE jobs to GH free runners

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/operator#407]
Our non-TEE [ccruntime_e2e](https://github.com/confidential-containers/operator/blob/main/.github/workflows/ccruntime_e2e.yaml) are configured to use az-ubuntu-2004 and az-ubuntu-2204 runners, hence they are instantiated VMs on Azure (via GARM).  Recently Github free runners are enabled with nested virtualization, meaning we can migrate these jobs from GARM to free runners (saving costs and lower maintenance).

It may be needed to adapt our Ansible scripts because the free runners comes with some softwares that may conflict with ours. For example, docker and containerd.

**Comment by ldoktor** [comment]
I'm struggling to make this work. First problem was disk space, I got around it by uninstalling unneeded packages, then also by using slower but bigger `/mnt` via a symlink. Now it seems to be running but it never uninstalls the operator: https://github.com/ldoktor/coco-operator/actions/runs/10283311141/job/28456863479?pr=4 I'll resume tomorrow.

**Comment by wainersm** [comment]
Hi @ldoktor !

Now that uninstall problem is fixed, could you give it another try?

This migration is specially important now because GARM started failing again...
