### ISSUE TITLE
COCO first release: Operator container image

### ISSUE THREAD

**Issue by ariel-adam** [confidential-containers/operator#41]
We need to create a pipeline for creating the image (automatically), we expect this to be a small effort 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jensfr** [comment]
For the operator image we now have a build trigger in quay.io that will build a new image on every merge to the  main branch. 
On the day of the release we will tag an image with the version number. 

Not marking it as done yet, as I want to test the trigger one more time.

**Comment by bpradipt** [comment]
@jensfr the trigger is working fine. Attaching the screenshot of the latest build

![image](https://user-images.githubusercontent.com/9287071/187935378-42a11b2c-a20c-46c3-9ff6-c884db9c2901.png)

Anything else you want to test or can we close this issue ?

**Comment by jensfr** [comment]
@bpradipt looks good, I think we can close it
