### ISSUE TITLE
COCO first release: updating the ccruntime yaml

### ISSUE THREAD

**Issue by ariel-adam** [confidential-containers/operator#43]
Updating the  ccruntime yaml to point to the correct CC runtime payload image.
This is mostly ready and needs to be updated for the release version - small effort 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bpradipt** [comment]
This is dependent on https://github.com/confidential-containers/operator/issues/44
Once the Kata payload with required bits is available, we will update the ccruntime.yaml

**Comment by bpradipt** [comment]
ccruntime.yaml is updated with payload image with successful CI runs- https://github.com/confidential-containers/operator/pull/96
