### ISSUE TITLE
COCO first release: Base container runtime

### ISSUE THREAD

**Issue by ariel-adam** [confidential-containers/operator#45]
Container image with custom containerd (or crio)  if required
This is mainly a packaging effort and small 

Sub issues that we must track before we consider this effort done:
- [x] https://github.com/kata-containers/kata-containers/pull/4513
- [x] https://github.com/kata-containers/tests/issues/4875
- [x] https://github.com/kata-containers/kata-containers/issues/4489
- [x] https://github.com/fidencio/container-engine-for-cc-payload/issues/1
- [ ] ...

**Comment by fidencio** [comment]
This has been done as part of https://github.com/fidencio/container-engine-for-cc-payload

We may need to update containerd to a newer version, as soon as https://github.com/kata-containers/kata-containers/pull/4490 gets merged.

For this task I don't think we need a specific CI, as this will be tested end-to-end **and** this solution should be **temporary** till we rely on upstream containerd, as soon as it's out.

**Comment by fidencio** [comment]
`quay.io/confidential-containers/container-engine-for-cc-payload:2022062810351656405327` is the image containing an up-to-date version of the patched containerd (based in containerd's official v1.6.6 release).
