### ISSUE TITLE
Add a CI pipeline for running the kata-containers tests on an Operator install environment 

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/operator#47]
I chatted with @fidencio about the [confidential-containers first release](https://docs.google.com/presentation/d/1vVN97q3bosJbjyco4dd_25PfnIYNaK3Kg_wCAmvmS4c/edit#slide=id.g132c3a0b3c7_0_5) CI/CD requirements and this was one of the items that we felt is required. We are also eager for feedback from @wainersm once he returns.

### Description

In order to test out the CC releases, which are released from the operator as the entry point to CC, we need a pipeline to test that they work. We'll need to extend the test cases that we work with, but to start with we should look to run the Kubernetes kata-containers tests (or a subset of them) on an environment that is installed with the operator. This has a dependency on having a confidential-containers pipeline available (which is discussed in https://github.com/confidential-containers/community/issues/52), but assuming we have that I think the flow of the job is something like:
- Install an operator pre-requisites (just golang? Can/should we re-use [`install_go.sh`](https://github.com/kata-containers/tests/blob/main/.ci/install_go.sh), or are we de-coupled from the kata version requirements so that it isn't worth it?)
- Build and CC operator 'release' (following the [process documented](https://github.com/confidential-containers/operator/blob/main/docs/DEVELOPMENT.md)?) I think this should pick up the kata-deploy image generated from https://github.com/kata-containers/kata-containers/issues/3992?
- Install Kubernetes in a test environment. We could potentially use [`install_kubernetes.sh`](https://github.com/kata-containers/tests/blob/main/.ci/install_kubernetes.sh) to do this.
- Set-up a Kubernetes cluster. Without knowing where we'll run these tests it's difficult to tell, but starting with a single node cluster seems reasonable. We might be able to use some of the logic in [`init.sh`](https://github.com/kata-containers/tests/blob/main/integration/kubernetes/init.sh), but we'd need to strip out some functionality (e.g. `check_processes` which uses the `kata-runtime`, creation of the kata runtimeClass)
- Install the CC operator from the release we created earlier (following the [install docs](https://github.com/confidential-containers/operator/blob/main/docs/INSTALL.md)?)
- Run the Kata-containers and/or Kata-containers CC Kubernetes tests. As long as we set-up the correct environment variables we might be able to use the [kata-containers/tests Makefile](https://github.com/kata-containers/tests/blob/main/Makefile) and call `make cc-kubernetes` (and `make kubernetes`?)

### Questions
- What variants of the job do we have? Our core use cases are: 
  - **Developer** - Run CC on your laptop, no confidential computing HW deps
  - **Local** - Run CC with local/offline attestation, no CC HW deps
  - **Production** (dev preview) - Run CC with remote attestation, on top of CC HW
 so I guess these would be a good start
- What platforms do we want to test on to start with? We currently test [kata-containers CCv0](http://jenkins.katacontainers.io/view/CCv0/) on Ubuntu+containerd, Fedora+Crio, ubuntu+firecracker for regression purposes and the CC specific tests are just on Ubuntu x86. Should we add more OSes, architectures, hypervisors, CRIs? We also want to support TEEs, starting with TDX, AMD-SEV and then s390x?

**Comment by wainersm** [comment]
Hi @arronwy , @BbolroC @ryansavino ,

I'm starting this comment because I wanted to have defined where the pipeline run.
 
@arronwy my understand is that the CI pipeline discussed here, for TDX, will run behind the firewall just like the TDX pipeline on Kata Containers, still in Jenkins. Am I right?

@BbolroC does s390x should run behind the curtains too? If so, does it use Jenkins as well? 

As for SEV, we already have a machine on Kata's Jenkins. @ryansavino can we use that machine for this operator CI? or perhaps we could be blessed with another machine? :D

Still about SEV, @fidencio, do you think we can have the pipeline for SEV running on kata's jenkins? Essentially I am trying to determine if we will need a machine self-hosted on Github and implement a action.

**Comment by BbolroC** [comment]
@wainersm yes, we are preparing an instance behind a firewall and will try what was advised by @arronwy for TDX CI via Jenkins.

**Comment by wainersm** [comment]
> I chatted with @fidencio about the [confidential-containers first release](https://docs.google.com/presentation/d/1vVN97q3bosJbjyco4dd_25PfnIYNaK3Kg_wCAmvmS4c/edit#slide=id.g132c3a0b3c7_0_5) CI/CD requirements and this was one of the items that we felt is required. We are also eager for feedback from @wainersm once he returns.
> ### Description
> 
> In order to test out the CC releases, which are released from the operator as the entry point to CC, we need a pipeline to test that they work. We'll need to extend the test cases that we work with, but to start with we should look to run the Kubernetes kata-containers tests (or a subset of them) on an environment that is installed with the operator. This has a dependency on having a confidential-containers pipeline available (which is discussed in [confidential-containers/community#52](https://github.com/confidential-containers/community/issues/52)), but assuming we have that I think the flow of the job is something like:
> 
>     * Install an operator pre-requisites (just golang? Can/should we re-use [`install_go.sh`](https://github.com/kata-containers/tests/blob/main/.ci/install_go.sh), or are we de-coupled from the kata version requirements so that it isn't worth it?)
> 

I bet the golang requirement for the operator is dependent of the Operator SDK version used, so de-coupled from kata version.

>     * Build and CC operator 'release' (following the [process documented](https://github.com/confidential-containers/operator/blob/main/docs/DEVELOPMENT.md)?) I think this should pick up the kata-deploy image generated from [kata-deploy: Provide a kata-deploy image to be used with the Confidential Containers operator kata-containers/kata-containers#3992](https://github.com/kata-containers/kata-containers/issues/3992)?
> 

I'd like a clarification on "pick up the kata-deploy image generated". Will this pipeline build the kata-deploy image? Or the image is already built (e.g. have a post-merge job on Kata Containers that builds kata-deploy and push the image to quay.io)?

>     * Install Kubernetes in a test environment. We could potentially use [`install_kubernetes.sh`](https://github.com/kata-containers/tests/blob/main/.ci/install_kubernetes.sh) to do this.
> 

I like the idea of reusing kata's kubernetes install script because we grant it is tested with same version and configuration as the other CC jobs on Kata side. However we create a dependency to kata that might cause problems: suppose that a change for the script lands on kata side, days later this pipeline is triggered and only then we notice it broke us. This example bring us the opportunity to discuss reverse dependency CI: should a pull request on kata triggers this operator pipeline? Or this can be initially mitigated with nightly builds on operator side, where at least we realize kata broke us within 24h at most, and only implement a reverse CI if those breakages become too frequent?

>     * Set-up a Kubernetes cluster. Without knowing where we'll run these tests it's difficult to tell, but starting with a single node cluster seems reasonable. We might be able to use some of the logic in [`init.sh`](https://github.com/kata-containers/tests/blob/main/integration/kubernetes/init.sh), but we'd need to strip out some functionality (e.g. `check_processes` which uses the `kata-runtime`, creation of the kata runtimeClass)
> 

Jobs for TDX and s390 will run behind the firewall, we don't have much control. However there are good changes we will run the SEV on a bare-metal node on kata's jenkins, thus I assume we should think in single node k8s.

>     * Install the CC operator from the release we created earlier (following the [install docs](https://github.com/confidential-containers/operator/blob/main/docs/INSTALL.md)?)
> 
>     * Run the Kata-containers and/or Kata-containers CC Kubernetes tests. As long as we set-up the correct environment variables we might be able to use the [kata-containers/tests Makefile](https://github.com/kata-containers/tests/blob/main/Makefile) and call `make cc-kubernetes` (and `make kubernetes`?)
> 

Good idea! I lost my faith on "simple, run the existing tests" while ago so I believe we will need a bunch of adaptations :)

I'm wondering if we need TEE specific tests. I know that there is this https://github.com/kata-containers/tests/blob/main/functional/tdx/run.sh for confidential guest for TDX.

> 
> ### Questions
> 
>     * What variants of the job do we have? Our core use cases are:
>       
>       * **Developer** - Run CC on your laptop, no confidential computing HW deps
>       * **Local** - Run CC with local/offline attestation, no CC HW deps
>       * **Production** (dev preview) - Run CC with remote attestation, on top of CC HW
>         so I guess these would be a good start
> 
>     * What platforms do we want to test on to start with? We currently test [kata-containers CCv0](http://jenkins.katacontainers.io/view/CCv0/) on Ubuntu+containerd, Fedora+Crio, ubuntu+firecracker for regression purposes and the CC specific tests are just on Ubuntu x86. Should we add more OSes, architectures, hypervisors, CRIs? We also want to support TEEs, starting with TDX, AMD-SEV and then s390x?

I will be figuring out with the red hat team if we want Fedora + CRIO on this first release. On long term I bet yes, we will need tests on that combination.

Regarding hypervisors I believe TDX is (will be) testing on Cloud Hypervisor. Right @fidencio? And on SEV it will be Ubuntu + QEMU. @ryansavino ?

**Comment by ryansavino** [comment]
ubuntu qemu for SEV for now. We'll work on enabling other hypervisors, but most likely nothing else before the first release.

**Comment by arronwy** [comment]
> Hi @arronwy , @BbolroC @ryansavino ,
> 
> I'm starting this comment because I wanted to have defined where the pipeline run.
> 
> @arronwy my understand is that the CI pipeline discussed here, for TDX, will run behind the firewall just like the TDX pipeline on Kata Containers, still in Jenkins. Am I right?

Yes, TDX CI pipeline will be in a Jenkins server and send build results to github Kata Conainers project

**Comment by stevenhorsman** [comment]
A few of my initial thoughts based on some of the questions that @wainersm raised:

> > ```
> > * Build and CC operator 'release' (following the [process documented](https://github.com/confidential-containers/operator/blob/main/docs/DEVELOPMENT.md)?) I think this should pick up the kata-deploy image generated from [kata-deploy: Provide a kata-deploy image to be used with the Confidential Containers operator kata-containers/kata-containers#3992](https://github.com/kata-containers/kata-containers/issues/3992)?
> > ```
> 
> I'd like a clarification on "pick up the kata-deploy image generated". Will this pipeline build the kata-deploy image? Or the image is already built (e.g. have a post-merge job on Kata Containers that builds kata-deploy and push the image to quay.io)?
> 

@fidencio - keep me honest here, but I think what we discussed was more like get this to run after the image was created. I think Jens mentioned yesterday that he set up an operator build trigger on the quay image, so maybe we could use something this rather than hooking it directly into the kata pipeline?

> > ```
> > * Install Kubernetes in a test environment. We could potentially use [`install_kubernetes.sh`](https://github.com/kata-containers/tests/blob/main/.ci/install_kubernetes.sh) to do this.
> > ```
> 
> I like the idea of reusing kata's kubernetes install script because we grant it is tested with same version and configuration as the other CC jobs on Kata side. However we create a dependency to kata that might cause problems: suppose that a change for the script lands on kata side, days later this pipeline is triggered and only then we notice it broke us. This example bring us the opportunity to discuss reverse dependency CI: should a pull request on kata triggers this operator pipeline? Or this can be initially mitigated with nightly builds on operator side, where at least we realize kata broke us within 24h at most, and only implement a reverse CI if those breakages become too frequent?
> 

Yeah, this is going to be a balancing act we have in a few cases - it is convenient to re-use kata utils, to keep version consistency and avoid duplication, but the coupling could cause problems. Maybe we should be considering a completely different approach for the operator and maybe use something like kind to create the test cluster? I'm not sure if there would be problems with the nested virtualisation and TEEs though with that approach? I guess if nothing else this is a good opportunity to try some different approaches and if they work well feed them back into Kata CI?

**Comment by ryansavino** [comment]
> As for SEV, we already have a machine on Kata's Jenkins. @ryansavino can we use that machine for this operator CI? or perhaps we could be blessed with another machine? :D

Yes, we can keep the current system reserved for kata cc CI and the operator CI. We should be able to provide an additional system as resources become constrained.

**Comment by wainersm** [comment]
I am working on that...I hope to have something working by next week.

**Comment by wainersm** [comment]
There was created the following jobs on Kata's Jenkins to run the tests for, respectively, kata-clh, kata-qemu, kata-qemu-sev runtime classes:

* [confidential-containers-operator-main-ubuntu-20.04-x86_64-containerd_kata-clh-PR](http://jenkins.katacontainers.io/job/confidential-containers-operator-main-ubuntu-20.04-x86_64-containerd_kata-clh-PR)
* [confidential-containers-operator-main-ubuntu-20.04-x86_64-containerd_kata-qemu-PR](http://jenkins.katacontainers.io/job/confidential-containers-operator-main-ubuntu-20.04-x86_64-containerd_kata-qemu-PR)
* [confidential-containers-operator-main-ubuntu-20.04_sev-x86_64-containerd_kata-qemu-sev-PR](http://jenkins.katacontainers.io/job/confidential-containers-operator-main-ubuntu-20.04_sev-x86_64-containerd_kata-qemu-sev-PR)

Those jobs are generated out of templates from Kata's jobs-builder: https://github.com/kata-containers/ci/tree/main/jobs-builder

Apart from those, Intel maintain jobs for TDX behind the firewall.

All in all, we have coverage for all the runtime classes.

The testing/CI scripts are hosted in https://github.com/confidential-containers/operator/tree/main/tests/e2e

The tests themselves are mostly the same as ran in Kata CI, with adaptations.  They are hosted in https://github.com/kata-containers/tests
