### ISSUE TITLE
cc-operator-pre-install-daemon-* pod is left behind after deleting the `ccruntime.yaml` file

### ISSUE THREAD

**Issue by fidencio** [confidential-containers/operator#49]
**Describe the bug**
After doing a `kubectl delete -f ccruntime.yaml` the pre-install-daemon pod is left behind, in running state.

**To Reproduce**
1. Deploy the operator
2. Deploy the CRD
3. Delete the CRD
4. Check the pods that are still running

**Describe the results you expected**
When removing the CRD, no pods should be left behind.

**Describe the results you received:**
```
$ kubectl get pods -n confidential-containers-system
NAME                                             READY   STATUS    RESTARTS      AGE
cc-operator-controller-manager-dc4846d94-d2l98   2/2     Running   3 (17m ago)   23m
cc-operator-pre-install-daemon-9j75w             1/1     Running   0             21m

```

**Comment by ariel-adam** [comment]
@fidencio is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?
