### ISSUE TITLE
Separate RuntimeClass for Kata remote hypervisor (aka peer-pods)

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/operator#56]
Currently Operator creates kata, kata-qemu and kata-clh runtimeclasses. This issue is to discuss whether we need a separate runtimeclass for peer-pods and what should we call it ?

**Comment by jensfr** [comment]
What would we use it for? to call kata with different parameters?

**Comment by fidencio** [comment]
Would it require a new configuration on the Kata Containers side?

**Comment by bpradipt** [comment]
> What would we use it for? to call kata with different parameters?

Yes..
