### ISSUE TITLE
RuntimeClass is not being set on k8s 1.25

### ISSUE THREAD

**Issue by snir911** [confidential-containers/operator#62]
**Describe the bug**
The operator is silently failing to set the runtimeclass objects on **1.25** k8s, although finalizers are added as expected

**To Reproduce**
1. deploy the operator
2. deploy the ccruntime CR

**Describe the results you expected**
kata-clh,kata-qemu,kata runtimeclass would be added

**Describe the results you received:**
`kubectl get runtimeclass` returns nothing
 
**Additional context**
Tested with peer-pods

**Comment by fidencio** [comment]
I faced the very same issue with confidential containers.

**Comment by bpradipt** [comment]
The issue is due to using deprecated api library in the code `nodeapi k8s.io/api/node/v1beta1`
@fidencio tried the fix in @snir911 environment and it worked. Can you try this in your environment 
```
kubectl set image deployment/cc-operator-controller-manager  -n confidential-containers-system manager=quay.io/bpradipt/cc-operator:latest
```

**Comment by bpradipt** [comment]
There are additional changes w.r.to latest k8s apis. I'll do some more investigations before raising a PR
