### ISSUE TITLE
Add instructions to deploy a sample encrypted container image

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/operator#77]
Currently we only have instructions to deploy and verify the operator.  Having instructions to deploy a sample workload  like what we use for CI will be a good addition.

**Comment by stevenhorsman** [comment]
I think this is ready to close after https://github.com/confidential-containers/documentation/pull/60 has merged. Is there anything else you think we need @bpradipt?

**Comment by bpradipt** [comment]
@stevenhorsman thanks a lot. I think we can close this issue.
