### ISSUE TITLE
Operator CI installing old bats version 

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/operator#83]
The operator CI lists `bats` as a test dependency (see `install_test_deps.yml`), which causes `bats` to be installed via apt. Unfortunately apt tracks an old version of bats, which does not match the one used in the kata CI and does not support the SEV tests. The kata CI uses a `.ci/install_bats.sh` script to install bats from upstream. Maybe we should do this in the operator CI as well? 

cc @wainersm @ryansavino

**Comment by wainersm** [comment]
@fitzthum what feature do you need that the old bats doesn't provide?

**Comment by fitzthum** [comment]
> what feature do you need that the old bats doesn't provide?

`setup_file` and `teardown_file`, which allow you to execute code before any of the tests in a file have run and after all the tests in a file have run. We use this to setup and teardown the KBS among other things. This feature narrowly missed being in release 1.2.0. Focal only has 1.1.0.
